# Use the official Python image from the Docker Hub
FROM python:3.12.7

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt ./

# Copy the rest of the application code into the container at /app
COPY . .

# Install the dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the Streamlit app when the container starts
CMD ["streamlit", "run", "application/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]